"""Pydantic models for MyDramaList API request/response payloads."""

from __future__ import annotations

from .auth import (
    ActionResult,
    AuthResponse,
    FriendProfile,
    FriendRole,
    FriendStatus,
    ProfileResponse,
    ProfileUploadResponse,
    Urls,
    UserProfileResponse,
)
from .base import Images, MDLModel, SearchEntry, resolve_image_url
from .feeds import (
    Article,
    ArticleAuthor,
    ArticleImages,
    Embed,
    Feed,
    FeedComment,
    FeedsResponse,
    MediaAttachment,
)
from .lists import (
    CustomListDetail,
    CustomListDetailItem,
    CustomListItem,
    CustomListLike,
    WatchStatusList,
)
from .misc import (
    ActivitiesResponse,
    Activity,
    AwardResponse,
    Coin,
    CoinResponse,
    Entries,
    Episodes,
    Leaderboard,
    MySubscription,
    PersonGiftProcess,
    PersonStats,
    PersonSummary,
    Quarter,
    Subscription,
    SubscriptionHistory,
    SubscriptionSettings,
)
from .reviews import (
    Author,
    Cast,
    Comment,
    CommentReplyResponse,
    CommentResponse,
    CreditsResponse,
    Crew,
    PostComment,
    Ratings,
    ReportRuleResponse,
    ReviewResponse,
)
from .social import (
    Chat,
    Friend,
    FriendAlt,
    Group,
    ModifiNotificationResponse,
    NotificationObject,
    NotificationResponse,
    Status,
    ThreadMessage,
    ThreadMessageResponse,
    ThreadUser,
)
from .titles import (
    LastActivity,
    Movie,
    MovieResourceResponse,
    MovieStatusType,
    MovieTitle,
    SyncWatchListResponse,
    TitleResponse,
    WatchPoints,
)

__all__ = [
    "MDLModel",
    "Images",
    "SearchEntry",
    "resolve_image_url",
    # auth & profile
    "AuthResponse",
    "ProfileResponse",
    "UserProfileResponse",
    "FriendProfile",
    "FriendRole",
    "FriendStatus",
    "ProfileUploadResponse",
    "Urls",
    "ActionResult",
    # titles & watchlist
    "TitleResponse",
    "MovieTitle",
    "Movie",
    "MovieResourceResponse",
    "MovieStatusType",
    "WatchPoints",
    "LastActivity",
    "SyncWatchListResponse",
    # reviews & comments
    "ReviewResponse",
    "Ratings",
    "Author",
    "Comment",
    "CommentResponse",
    "PostComment",
    "CommentReplyResponse",
    "Cast",
    "Crew",
    "CreditsResponse",
    "ReportRuleResponse",
    # custom lists
    "CustomListItem",
    "CustomListDetail",
    "CustomListDetailItem",
    "WatchStatusList",
    "CustomListLike",
    # feeds, articles, embeds
    "FeedsResponse",
    "Feed",
    "FeedComment",
    "MediaAttachment",
    "Article",
    "ArticleImages",
    "ArticleAuthor",
    "Embed",
    # social
    "Friend",
    "FriendAlt",
    "Status",
    "ThreadMessage",
    "ThreadMessageResponse",
    "ThreadUser",
    "Chat",
    "NotificationObject",
    "NotificationResponse",
    "ModifiNotificationResponse",
    "Group",
    # misc
    "Coin",
    "CoinResponse",
    "Activity",
    "ActivitiesResponse",
    "MySubscription",
    "Subscription",
    "SubscriptionHistory",
    "SubscriptionSettings",
    "PersonGiftProcess",
    "Entries",
    "Leaderboard",
    "Episodes",
    "Quarter",
    "PersonStats",
    "PersonSummary",
    "AwardResponse",
]
