"""Async client. The sync twin (``mdl._sync.client.MDLClient``) is generated by unasync."""

from __future__ import annotations

from typing import Optional

import httpx

from ..auth import TokenStore
from ..config import ClientConfig, Environment
from ._transport import AsyncTransport
from .resources.auth import AccountResource, AuthResource, UsersResource
from .resources.lists import CustomListsResource, WatchlistResource
from .resources.misc import (
    AwardsResource,
    CalendarResource,
    FlowersResource,
    LeaderboardResource,
    ReportsResource,
    SubscriptionResource,
)
from .resources.social import (
    ArticlesResource,
    FeedsResource,
    FriendsResource,
    GroupsResource,
    MessagesResource,
    NotificationsResource,
)
from .resources.titles import (
    CommentsResource,
    ExploreResource,
    ReviewsResource,
    SearchResource,
    TitlesResource,
)


class MDLClient:
    """Asynchronous MyDramaList API client.

    Resource groups are exposed as attributes, e.g. ``client.titles.get_title(123)``.
    Supply the app ``mdl-api-key`` explicitly or via the ``MDL_API_KEY`` env var.
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        *,
        app_version: Optional[str] = None,
        environment: Environment = Environment.PRODUCTION,
        device_id: Optional[str] = None,
        lang_code: Optional[str] = None,
        timeout: float = 30.0,
        token: Optional[str] = None,
        token_store: Optional[TokenStore] = None,
        http_client: Optional[httpx.AsyncClient] = None,
    ) -> None:
        config = ClientConfig.resolve(
            api_key,
            app_version=app_version,
            environment=environment,
            device_id=device_id,
            lang_code=lang_code,
            timeout=timeout,
        )
        self._transport = AsyncTransport(config, token_store, client=http_client)
        if token:
            self._transport.tokens.set_token(token)

        self.auth = AuthResource(self._transport)
        self.account = AccountResource(self._transport)
        self.users = UsersResource(self._transport)
        self.titles = TitlesResource(self._transport)
        self.search = SearchResource(self._transport)
        self.explore = ExploreResource(self._transport)
        self.reviews = ReviewsResource(self._transport)
        self.comments = CommentsResource(self._transport)
        self.watchlist = WatchlistResource(self._transport)
        self.custom_lists = CustomListsResource(self._transport)
        self.feeds = FeedsResource(self._transport)
        self.articles = ArticlesResource(self._transport)
        self.friends = FriendsResource(self._transport)
        self.messages = MessagesResource(self._transport)
        self.notifications = NotificationsResource(self._transport)
        self.groups = GroupsResource(self._transport)
        self.subscription = SubscriptionResource(self._transport)
        self.flowers = FlowersResource(self._transport)
        self.awards = AwardsResource(self._transport)
        self.reports = ReportsResource(self._transport)
        self.calendar = CalendarResource(self._transport)
        self.leaderboard = LeaderboardResource(self._transport)

    @property
    def config(self) -> ClientConfig:
        return self._transport.config

    @property
    def tokens(self) -> TokenStore:
        return self._transport.tokens

    async def aclose(self) -> None:
        await self._transport.aclose()

    async def __aenter__(self) -> "MDLClient":
        return self

    async def __aexit__(self, *exc: object) -> None:
        await self.aclose()
